# Generated by Django 4.2.6 on 2023-12-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('lastname', models.TextField()),
                ('firstname', models.TextField()),
                ('patronym', models.TextField()),
            ],
        ),
    ]
