# Generated by Django 4.2.6 on 2023-12-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab16', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='level_acces',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
