# Generated by Django 4.2.6 on 2023-12-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooker',
            fields=[
                ('id_cooker', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lastname', models.TextField()),
                ('firstname', models.TextField()),
                ('patronym', models.TextField()),
                ('specials', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id_dish', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kitchen.product')),
            ],
        ),
    ]
